//
//  ButtonStyleKit.h
//  ProjectName
//
//  Created by AuthorName on 2019/1/5.
//  Copyright © 2019 CompanyName. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import <UIKit/UIKit.h>



typedef enum : NSInteger
{
    ButtonStyleKitResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    ButtonStyleKitResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    ButtonStyleKitResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    ButtonStyleKitResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.

} ButtonStyleKitResizingBehavior;

extern CGRect ButtonStyleKitResizingBehaviorApply(ButtonStyleKitResizingBehavior behavior, CGRect rect, CGRect target);


@interface ButtonStyleKit : NSObject

// Colors
+ (UIColor*)color;

// Drawing Methods
+ (void)drawOnCanvas;
+ (void)drawOnCanvasWithFrame: (CGRect)targetFrame resizing: (ButtonStyleKitResizingBehavior)resizing;
+ (void)drawOffCanvas;
+ (void)drawOffCanvasWithFrame: (CGRect)targetFrame resizing: (ButtonStyleKitResizingBehavior)resizing;
+ (void)drawPreviousButton;
+ (void)drawPreviousButtonWithFrame: (CGRect)targetFrame resizing: (ButtonStyleKitResizingBehavior)resizing;
+ (void)drawNextButton;
+ (void)drawNextButtonWithFrame: (CGRect)targetFrame resizing: (ButtonStyleKitResizingBehavior)resizing;
+ (void)drawPlayButton;
+ (void)drawPlayButtonWithFrame: (CGRect)targetFrame resizing: (ButtonStyleKitResizingBehavior)resizing;
+ (void)drawPauseButton;
+ (void)drawPauseButtonWithFrame: (CGRect)targetFrame resizing: (ButtonStyleKitResizingBehavior)resizing;
+ (void)drawStopButton;
+ (void)drawStopButtonWithFrame: (CGRect)targetFrame resizing: (ButtonStyleKitResizingBehavior)resizing;

@end
