//
//  HeartStyleKit.h
//  ProjectName
//
//  Created by AuthorName on 2018/12/8.
//  Copyright © 2018 CompanyName. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import <UIKit/UIKit.h>



typedef enum : NSInteger
{
    HeartStyleKitResizingBehaviorAspectFit, //!< The content is proportionally resized to fit into the target rectangle.
    HeartStyleKitResizingBehaviorAspectFill, //!< The content is proportionally resized to completely fill the target rectangle.
    HeartStyleKitResizingBehaviorStretch, //!< The content is stretched to match the entire target rectangle.
    HeartStyleKitResizingBehaviorCenter, //!< The content is centered in the target rectangle, but it is NOT resized.

} HeartStyleKitResizingBehavior;

extern CGRect HeartStyleKitResizingBehaviorApply(HeartStyleKitResizingBehavior behavior, CGRect rect, CGRect target);


@interface HeartStyleKit : NSObject

// Colors
+ (UIColor*)color;

// Drawing Methods
+ (void)drawOnCanvas;
+ (void)drawOnCanvasWithFrame: (CGRect)targetFrame resizing: (HeartStyleKitResizingBehavior)resizing;
+ (void)drawOffCanvas;
+ (void)drawOffCanvasWithFrame: (CGRect)targetFrame resizing: (HeartStyleKitResizingBehavior)resizing;

@end
