//
//  HeartStyleKit.m
//  ProjectName
//
//  Created by AuthorName on 2018/12/8.
//  Copyright © 2018 CompanyName. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import "HeartStyleKit.h"


@implementation HeartStyleKit

#pragma mark Cache

static UIColor* _color = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _color = [UIColor colorWithRed: 0.513 green: 0.684 blue: 0.626 alpha: 1];

}

#pragma mark Colors

+ (UIColor*)color { return _color; }

#pragma mark Drawing Methods

+ (void)drawOnCanvas
{
    [HeartStyleKit drawOnCanvasWithFrame: CGRectMake(0, 0, 60, 54) resizing: HeartStyleKitResizingBehaviorStretch];
}

+ (void)drawOnCanvasWithFrame: (CGRect)targetFrame resizing: (HeartStyleKitResizingBehavior)resizing
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();
    
    //// Resize to Target Frame
    CGContextSaveGState(context);
    CGRect resizedFrame = HeartStyleKitResizingBehaviorApply(resizing, CGRectMake(0, 0, 60, 54), targetFrame);
    CGContextTranslateCTM(context, resizedFrame.origin.x, resizedFrame.origin.y);
    CGContextScaleCTM(context, resizedFrame.size.width / 60, resizedFrame.size.height / 54);


    //// Color Declarations
    UIColor* fillColor = [UIColor colorWithRed: 0.937 green: 0 blue: 0 alpha: 1];

    //// Page
    {
        //// OnShape Drawing
        UIBezierPath* onShapePath = [UIBezierPath bezierPath];
        [onShapePath moveToPoint: CGPointMake(60.04, 18.14)];
        [onShapePath addCurveToPoint: CGPointMake(42.56, 0.02) controlPoint1: CGPointMake(60.04, 8.15) controlPoint2: CGPointMake(52.19, 0.02)];
        [onShapePath addCurveToPoint: CGPointMake(30.04, 5.57) controlPoint1: CGPointMake(37.8, 0.02) controlPoint2: CGPointMake(33.3, 2.07)];
        [onShapePath addCurveToPoint: CGPointMake(17.53, 0.02) controlPoint1: CGPointMake(26.79, 2.07) controlPoint2: CGPointMake(22.28, 0.02)];
        [onShapePath addCurveToPoint: CGPointMake(0.04, 18.14) controlPoint1: CGPointMake(7.89, 0.02) controlPoint2: CGPointMake(0.04, 8.15)];
        [onShapePath addCurveToPoint: CGPointMake(0.1, 19.02) controlPoint1: CGPointMake(0.04, 18.48) controlPoint2: CGPointMake(0.08, 18.77)];
        [onShapePath addCurveToPoint: CGPointMake(0.09, 19.27) controlPoint1: CGPointMake(0.1, 19.1) controlPoint2: CGPointMake(0.09, 19.18)];
        [onShapePath addCurveToPoint: CGPointMake(1.37, 25.04) controlPoint1: CGPointMake(0.09, 21.03) controlPoint2: CGPointMake(0.52, 22.98)];
        [onShapePath addCurveToPoint: CGPointMake(1.45, 25.26) controlPoint1: CGPointMake(1.39, 25.12) controlPoint2: CGPointMake(1.42, 25.19)];
        [onShapePath addCurveToPoint: CGPointMake(28.16, 53.38) controlPoint1: CGPointMake(6.78, 38.02) controlPoint2: CGPointMake(27.29, 52.7)];
        [onShapePath addCurveToPoint: CGPointMake(29.99, 54) controlPoint1: CGPointMake(28.7, 53.79) controlPoint2: CGPointMake(29.35, 54)];
        [onShapePath addCurveToPoint: CGPointMake(31.85, 53.36) controlPoint1: CGPointMake(30.65, 54) controlPoint2: CGPointMake(31.3, 53.79)];
        [onShapePath addCurveToPoint: CGPointMake(57.03, 28.31) controlPoint1: CGPointMake(32.59, 52.78) controlPoint2: CGPointMake(50.09, 40.2)];
        [onShapePath addCurveToPoint: CGPointMake(57.66, 27.18) controlPoint1: CGPointMake(57.29, 27.91) controlPoint2: CGPointMake(57.49, 27.52)];
        [onShapePath addCurveToPoint: CGPointMake(57.83, 26.86) controlPoint1: CGPointMake(57.72, 27.07) controlPoint2: CGPointMake(57.77, 26.97)];
        [onShapePath addLineToPoint: CGPointMake(57.85, 26.82)];
        [onShapePath addCurveToPoint: CGPointMake(57.92, 26.7) controlPoint1: CGPointMake(57.87, 26.78) controlPoint2: CGPointMake(57.9, 26.73)];
        [onShapePath addCurveToPoint: CGPointMake(58.93, 24.4) controlPoint1: CGPointMake(58.34, 25.89) controlPoint2: CGPointMake(58.67, 25.14)];
        [onShapePath addCurveToPoint: CGPointMake(60.01, 19.27) controlPoint1: CGPointMake(59.65, 22.52) controlPoint2: CGPointMake(60.01, 20.84)];
        [onShapePath addCurveToPoint: CGPointMake(59.99, 18.95) controlPoint1: CGPointMake(60.01, 19.15) controlPoint2: CGPointMake(60, 19.04)];
        [onShapePath addCurveToPoint: CGPointMake(60.04, 18.14) controlPoint1: CGPointMake(60.02, 18.75) controlPoint2: CGPointMake(60.04, 18.47)];
        [onShapePath closePath];
        [fillColor setFill];
        [onShapePath fill];
    }
    
    CGContextRestoreGState(context);

}

+ (void)drawOffCanvas
{
    [HeartStyleKit drawOffCanvasWithFrame: CGRectMake(0, 0, 60, 54) resizing: HeartStyleKitResizingBehaviorStretch];
}

+ (void)drawOffCanvasWithFrame: (CGRect)targetFrame resizing: (HeartStyleKitResizingBehavior)resizing
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();
    
    //// Resize to Target Frame
    CGContextSaveGState(context);
    CGRect resizedFrame = HeartStyleKitResizingBehaviorApply(resizing, CGRectMake(0, 0, 60, 54), targetFrame);
    CGContextTranslateCTM(context, resizedFrame.origin.x, resizedFrame.origin.y);
    CGContextScaleCTM(context, resizedFrame.size.width / 60, resizedFrame.size.height / 54);


    //// Page
    {
        //// OnShape Drawing
        UIBezierPath* onShapePath = [UIBezierPath bezierPath];
        [onShapePath moveToPoint: CGPointMake(60.04, 18.14)];
        [onShapePath addCurveToPoint: CGPointMake(42.56, 0.02) controlPoint1: CGPointMake(60.04, 8.15) controlPoint2: CGPointMake(52.19, 0.02)];
        [onShapePath addCurveToPoint: CGPointMake(30.04, 5.57) controlPoint1: CGPointMake(37.8, 0.02) controlPoint2: CGPointMake(33.3, 2.07)];
        [onShapePath addCurveToPoint: CGPointMake(17.53, 0.02) controlPoint1: CGPointMake(26.79, 2.07) controlPoint2: CGPointMake(22.28, 0.02)];
        [onShapePath addCurveToPoint: CGPointMake(0.04, 18.14) controlPoint1: CGPointMake(7.89, 0.02) controlPoint2: CGPointMake(0.04, 8.15)];
        [onShapePath addCurveToPoint: CGPointMake(0.1, 19.02) controlPoint1: CGPointMake(0.04, 18.48) controlPoint2: CGPointMake(0.08, 18.77)];
        [onShapePath addCurveToPoint: CGPointMake(0.09, 19.27) controlPoint1: CGPointMake(0.1, 19.1) controlPoint2: CGPointMake(0.09, 19.18)];
        [onShapePath addCurveToPoint: CGPointMake(1.37, 25.04) controlPoint1: CGPointMake(0.09, 21.03) controlPoint2: CGPointMake(0.52, 22.98)];
        [onShapePath addCurveToPoint: CGPointMake(1.45, 25.26) controlPoint1: CGPointMake(1.39, 25.12) controlPoint2: CGPointMake(1.42, 25.19)];
        [onShapePath addCurveToPoint: CGPointMake(28.16, 53.38) controlPoint1: CGPointMake(6.78, 38.02) controlPoint2: CGPointMake(27.29, 52.7)];
        [onShapePath addCurveToPoint: CGPointMake(29.99, 54) controlPoint1: CGPointMake(28.7, 53.79) controlPoint2: CGPointMake(29.35, 54)];
        [onShapePath addCurveToPoint: CGPointMake(31.85, 53.36) controlPoint1: CGPointMake(30.65, 54) controlPoint2: CGPointMake(31.3, 53.79)];
        [onShapePath addCurveToPoint: CGPointMake(57.03, 28.31) controlPoint1: CGPointMake(32.59, 52.78) controlPoint2: CGPointMake(50.09, 40.2)];
        [onShapePath addCurveToPoint: CGPointMake(57.66, 27.18) controlPoint1: CGPointMake(57.29, 27.91) controlPoint2: CGPointMake(57.49, 27.52)];
        [onShapePath addCurveToPoint: CGPointMake(57.83, 26.86) controlPoint1: CGPointMake(57.72, 27.07) controlPoint2: CGPointMake(57.77, 26.97)];
        [onShapePath addLineToPoint: CGPointMake(57.85, 26.82)];
        [onShapePath addCurveToPoint: CGPointMake(57.92, 26.7) controlPoint1: CGPointMake(57.87, 26.78) controlPoint2: CGPointMake(57.9, 26.73)];
        [onShapePath addCurveToPoint: CGPointMake(58.93, 24.4) controlPoint1: CGPointMake(58.34, 25.89) controlPoint2: CGPointMake(58.67, 25.14)];
        [onShapePath addCurveToPoint: CGPointMake(60.01, 19.27) controlPoint1: CGPointMake(59.65, 22.52) controlPoint2: CGPointMake(60.01, 20.84)];
        [onShapePath addCurveToPoint: CGPointMake(59.99, 18.95) controlPoint1: CGPointMake(60.01, 19.15) controlPoint2: CGPointMake(60, 19.04)];
        [onShapePath addCurveToPoint: CGPointMake(60.04, 18.14) controlPoint1: CGPointMake(60.02, 18.75) controlPoint2: CGPointMake(60.04, 18.47)];
        [onShapePath closePath];
        [HeartStyleKit.color setFill];
        [onShapePath fill];
    }
    
    CGContextRestoreGState(context);

}

@end



CGRect HeartStyleKitResizingBehaviorApply(HeartStyleKitResizingBehavior behavior, CGRect rect, CGRect target)
{
    if (CGRectEqualToRect(rect, target) || CGRectEqualToRect(target, CGRectZero))
        return rect;

    CGSize scales = CGSizeZero;
    scales.width = ABS(target.size.width / rect.size.width);
    scales.height = ABS(target.size.height / rect.size.height);

    switch (behavior)
    {
        case HeartStyleKitResizingBehaviorAspectFit:
        {
            scales.width = MIN(scales.width, scales.height);
            scales.height = scales.width;
            break;
        }
        case HeartStyleKitResizingBehaviorAspectFill:
        {
            scales.width = MAX(scales.width, scales.height);
            scales.height = scales.width;
            break;
        }
        case HeartStyleKitResizingBehaviorStretch:
            break;
        case HeartStyleKitResizingBehaviorCenter:
        {
            scales.width = 1;
            scales.height = 1;
            break;
        }
    }

    CGRect result = CGRectStandardize(rect);
    result.size.width *= scales.width;
    result.size.height *= scales.height;
    result.origin.x = target.origin.x + (target.size.width - result.size.width) / 2;
    result.origin.y = target.origin.y + (target.size.height - result.size.height) / 2;
    return result;
}
